### ISSUE TITLE
WavesetEvent.loadDialog?

### ISSUE THREAD

**Issue by IanMFraser** [musikinformatik/WavesetsEvent#3]
Hi,

I'd like to use loadDialog to search for sound files to use with a WavesetsEvent GUI. Is it possible to add a loadDialog method to WavesetsEvent or is there an appropriate workaround?

**Comment by telephon** [comment]
It's quite easy:
```supercollider
Dialog.openPanel({ | path | ~wavesets = WavesetsEvent.read(path) });
```

**Comment by IanMFraser** [comment]
Thank you, Julian! I had a feeling it was a simple solution.
