### ISSUE TITLE
Pwavesets compatible with Pbindef? 

### ISSUE THREAD

**Issue by IanMFraser** [musikinformatik/WavesetsEvent#4]
Hi,

Is there a way to use WavesetsEvent in a Pbindef? I'm sorry if this is obvious but I'm not quite sure how to make this work given that the Pbind is wrapped within Pwavesets. I'm trying to gain control of individual keys while the pattern is playing without having to change the entire Pbind.

**Comment by telephon** [comment]
You can wrap a `Pdef` that refers to your `Pbindef`:

```
Pbindef(\x, ...);
Pwavesets(Pdef(\x)).play
```

or wrap it one mor time if you need several parallel references:
```
Pbindef(\x, ...);
Pdef(\y, Pwavesets(Pdef(\x)));
Pdef(\y).play;
```

**Comment by IanMFraser** [comment]
Thanks, Julian. This solution works great.  I guess most of my confusion is with what Pwavesets is actually doing and how it should be used.

**Comment by telephon** [comment]
yes, the documentation is a bit sketchy. Pwavesets just filters an event stream, so you can put it in any place where there is an event stream.
